with open('docker-compose.sandbox.yml', 'w', encoding='utf-8') as f:
    f.write('version: "3.8"\n')
    f.write('services:\n')
    f.write('  executor:\n')
    f.write('    image: zarabotok-sandbox:latest\n')
    f.write('    build:\n')
    f.write('      context: zarabotok/pipeline_v3\n')
    f.write('      dockerfile: Dockerfile.sandbox\n')
    f.write('    network_mode: none\n')
    f.write('    read_only: true\n')
    f.write('    user: "1001:1001"\n')
    f.write('    mem_limit: 1g\n')
    f.write('    memswap_limit: 1g\n')
    f.write('    cap_drop:\n')
    f.write('      - ALL\n')
    f.write('    security_opt:\n')
    f.write('      - no-new-privileges:true\n')
    f.write('    volumes:\n')
    f.write('      - ./zarabotok/pipeline_v3/workspace:/workspace:rw\n')
    f.write('    working_dir: /workspace\n')
    f.write('    command: sh -c "echo sandbox isolated; python -c \'print(\\\'executor smoke ok\\\')\'"\n')
    f.write('    healthcheck:\n')
    f.write('      test: ["CMD", "python", "-c", "print(\'health ok\')"]\n')
    f.write('      interval: 30s\n')
    f.write('      timeout: 5s\n')
    f.write('      retries: 3\n')
    f.write('    restart: unless-stopped\n')
print('wrote docker-compose.sandbox.yml')
